[files]
extend-exclude = [
  "CHANGELOG.md",
  "bin/lesspipe.sh",
  "bin/rsync_tmbackup.sh",
  "bin/trans",
  "bin/xpanes",
  "dotfiles/.aliases",
  "dotfiles/.gitconfig",
  "etc/prompts/",
  "etc/ptpython/config.py",
  "etc/nvim/lazy-lock.json",
  "ui/macos/write_macos_defaults"
]
