[cache]
dir = "~/Library/Caches/tlrc"
mirror = "https://github.com/tldr-pages/tldr/releases/latest/download"
auto_update = true
defer_auto_update = false
max_age = 336
languages = []

[output]
show_title = true
platform_title = false
show_hyphens = false
example_prefix = "- "
line_length = 0
compact = false
option_style = "long"
raw_markdown = false

[indent]
title = 2
description = 2
bullet = 2
example = 4

# Ayu Dark theme colors
# Based on https://github.com/ayu-theme/ayu-colors/blob/master/src/dark.ts
#
# Style for the title of the page (command name).
[style.title]
color = { hex = "AAD94C" }
background = "default"
bold = true
underline = false
italic = false
dim = false
strikethrough = false

# Style for the description of the page.
[style.description]
color = { hex = "BFBDB6" }
background = "default"
bold = false
underline = false
italic = false
dim = false
strikethrough = false

# Style for descriptions of examples.
[style.bullet]
color = { hex = "BFBDB6" }
background = "default"
bold = false
underline = false
italic = false
dim = false
strikethrough = false

# Style for command examples.
[style.example]
color = { hex = "FFB454" }
background = "default"
bold = false
underline = false
italic = false
dim = false
strikethrough = false

# Style for URLs inside the description.
[style.url]
color = { hex = "39BAE6" }
background = "default"
bold = false
underline = false
italic = false
dim = false
strikethrough = false

# Style for text surrounded by backticks (`).
[style.inline_code]
color = { hex = "FFB454" }
background = "default"
bold = false
underline = false
italic = false
dim = false
strikethrough = false

# Style for placeholders inside command examples.
[style.placeholder]
color = { hex = "D2A6FF" }
background = "default"
bold = false
underline = false
italic = false
dim = false
strikethrough = false
